{
 "title": "Saturation",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=~\"$namespace\"}, container_label_io_kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "p95 - Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95, sum(\n        rate(\n            istio_request_duration_milliseconds_bucket\n            {\n                destination_workload=~\"service-a\",\n                destination_workload_namespace=~\"golang|nodejs\",\n            }[1m])) by (le, destination_workload, destination_workload_namespace)\n    )",
     "legendFormat": "{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Service-A - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n            container_label_io_kubernetes_pod_name=~\"$pod\",\n            image!=\"\",\n            container_label_io_kubernetes_container_name!=\"istio-proxy\",\n            container_label_io_kubernetes_container_name=\"service-a\",\n            container_label_io_cri_containerd_kind=\"container\"\n        }[1m]\n        )\n    )\nby (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name,\n    container_label_io_kubernetes_pod_namespace\n    ) /\nsum(\n    container_spec_cpu_quota\n    {\n        container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n        container_label_io_kubernetes_pod_name=~\"$pod\",\n        container_label_io_kubernetes_container_name!=\"istio-proxy\",\n        container_label_io_kubernetes_container_name=\"service-a\",\n        image!=\"\",\n        container_label_io_cri_containerd_kind=\"container\"\n    } /\n    container_spec_cpu_period\n    {\n        container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n        container_label_io_kubernetes_pod_name=~\"$pod\",\n        container_label_io_kubernetes_container_name!=\"istio-proxy\",\n        container_label_io_kubernetes_container_name=\"service-a\",\n        image!=\"\",\n        container_label_io_cri_containerd_kind=\"container\"\n    }\n    )\nby (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name,\n    container_label_io_kubernetes_pod_namespace\n    )",
     "legendFormat": "{{ container_label_io_kubernetes_pod_namespace }}"
    }
   ]
  },
  {
   "title": "Service-A - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes\n{\n            container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n            container_label_io_kubernetes_pod_name=~\"$pod\",\n            image!=\"\",\n            container_label_io_kubernetes_container_name!=\"istio-proxy\",\n            container_label_io_kubernetes_container_name=\"service-a\",\n            container_label_io_cri_containerd_kind=\"container\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n            container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n            container_label_io_kubernetes_pod_name=~\"$pod\",\n            image!=\"\",\n            container_label_io_kubernetes_container_name!=\"istio-proxy\",\n            container_label_io_kubernetes_container_name=\"service-a\",\n            container_label_io_cri_containerd_kind=\"container\"\n}",
     "legendFormat": "{{ container_label_io_kubernetes_pod_namespace }}"
    }
   ]
  },
  {
   "title": "Service-B - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n            container_label_io_kubernetes_pod_name=~\"$pod\",\n            image!=\"\",\n            container_label_io_kubernetes_container_name!=\"istio-proxy\",\n            container_label_io_kubernetes_container_name=\"service-b\",\n            container_label_io_cri_containerd_kind=\"container\"\n        }[1m]\n        )\n    )\nby (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name,\n    container_label_io_kubernetes_pod_namespace\n    ) /\nsum(\n    container_spec_cpu_quota\n    {\n        container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n        container_label_io_kubernetes_pod_name=~\"$pod\",\n        container_label_io_kubernetes_container_name!=\"istio-proxy\",\n        container_label_io_kubernetes_container_name=\"service-b\",\n        image!=\"\",\n        container_label_io_cri_containerd_kind=\"container\"\n    } /\n    container_spec_cpu_period\n    {\n        container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n        container_label_io_kubernetes_pod_name=~\"$pod\",\n        container_label_io_kubernetes_container_name!=\"istio-proxy\",\n        container_label_io_kubernetes_container_name=\"service-b\",\n        image!=\"\",\n        container_label_io_cri_containerd_kind=\"container\"\n    }\n    )\nby (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name,\n    container_label_io_kubernetes_pod_namespace\n    )",
     "legendFormat": "{{ container_label_io_kubernetes_pod_namespace }}"
    }
   ]
  },
  {
   "title": "Service-B - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes\n{\n            container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n            container_label_io_kubernetes_pod_name=~\"$pod\",\n            image!=\"\",\n            container_label_io_kubernetes_container_name!=\"istio-proxy\",\n            container_label_io_kubernetes_container_name=\"service-b\",\n            container_label_io_cri_containerd_kind=\"container\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n            container_label_io_kubernetes_pod_namespace=~\"golang|nodejs\",\n            container_label_io_kubernetes_pod_name=~\"$pod\",\n            image!=\"\",\n            container_label_io_kubernetes_container_name!=\"istio-proxy\",\n            container_label_io_kubernetes_container_name=\"service-b\",\n            container_label_io_cri_containerd_kind=\"container\"\n}",
     "legendFormat": "{{ container_label_io_kubernetes_pod_namespace }}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload=~\"service-a\", destination_workload_namespace=~\"golang|nodejs\"}[1m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload_namespace }}"
    }
   ]
  }
 ]
}