apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-standard-ssd
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-standard-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-azdisk-deployment-standard-ssd
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webcontent
          mountPath: "/usr/share/nginx/html/web-app"
      volumes:
      - name: webcontent
        persistentVolumeClaim:
          claimName: pvc-azure-standard-ssd
