version: "2"

services:

  cups:
    image: ydkn/cups
    ports:
      - 631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - ./cups:/etc/cup
    environment:
      # El user y password por defecto son admin / admin
      - ADMIN_PASSWORD=admin
    restart: always
    privileged: true
