version: '3.8'

services:

  # Devops Tools
  devops_tools:
    container_name: devops_tools
    image: teamdigitale/devops-tools
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
    volumes:
      - .:/devops:rw
      - ${HOME}/.kube:/root/.kube:rw
      - ${HOME}/.azure:/root/.azure:rw
      - ${HOME}/.local/bin:/root/.local/bin:rw
      - ${HOME}/.gnupg:/root/.gnupg:rw
      - ${DPT_BOGUS_PATH}:/root/.password-store:rw
