---
- name: Run JUNOS configuration tasks
  connection: local
  gather_facts: false
  hosts: junos-r2
  roles: 
    - Juniper.junos

  tasks:
    - name: Retrieve the committed config
      juniper_junos_config:
        host: "{{ ansible_ssh_host  }}"
        user: "{{ ansible_ssh_user  }}"
        passwd: "{{ ansible_ssh_password  }}"
        retrieve: 'committed'
        diff: false
        check: false
        commit: false
 
      register: junos_output

    - name: print the lines
      debug:
        var: junos_output

...
