---
- name: Collect JUNOS Device Facts
  hosts: junos-r2
  connection: local
  gather_facts: no
  roles: 
    - Juniper.junos

  tasks:
    - name:
      junos_get_facts:
        host: "{{ ansible_ssh_host  }}"
        user: "{{ ansible_ssh_user  }}"
        passwd: "{{ ansible_ssh_password  }}"

      register: output

    - name: show output
      debug:
        var: output

...
