---
- name: Run JUNOS command and backup results
  connection: local
  gather_facts: false
  hosts: junos-r2
  roles: 
    - Juniper.junos

  tasks:
    - name: run commands
      juniper_junos_command:
        host: "{{ ansible_ssh_host  }}"
        user: "{{ ansible_ssh_user  }}"
        passwd: "{{ ansible_ssh_password  }}"
        commands: 
          - "show version"
          - "show route"
        formats:
          - "xml"
 
      register: junos_output

    - name: copy output to file
      copy: content="{{ junos_output }}" dest=./output/{{ inventory_hostname }}.txt

...
