tenant: ac360 # Enter your tenant name here
app: enterprise # Enter your application name here
service: demo-email-form

frameworkVersion: '>=1.38.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs10.x
  # credentials: ${secrets:aws-enterprise} # Enter an AWS Secret like this, after you create it in the Dashboard.

functions:
  formSubmit:
    handler: index.submit
    events:
      - http:
          path: submit
          method: post
          cors: true

plugins:
  # - serverless-finch # If you want to deploy the front-end uncomment this and the "custom" object below

# custom:
  # client:
    # bucketName: sfe-demo-email-form # If you want to deploy the front-end, change this to a universally unique AWS S3 bucket name
    # distributionFolder: ../frontend/build
