apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: wordpress 
    spec:
      containers:
      - name: wordpress 
        image: wordpress:php7.1-apache
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
