---
- name: EOS Command
  hosts: eos-1
  connection: local
  gather_facts: false
  
  tasks: 
    - name: EOS Command 
      eos_command: 
        commands: 
          - command: show version
            output: json
        provider: '{{ eos_connection  }}'
      register: output

    - name: show output
      debug:
        var: output
