version: '3'

services:

  traefik:
    image: traefik:${TRAEFIK_VERSION} # for use in production always use an specific version
    command: --docker --docker.domain=${DOMAIN} # domain to redirect the request
    ports:
      - ${HTTP_PORT}:80 # default port for reverse proxy
      - ${HTTPS_PORT}:443 # default port for reverse proxy
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE_ROUTE}:/traefik.toml # master file to save all the config for traefik
      - ${TRAEFIK_ACME_FILE_ROUTE}:/acme.json # autogenerate reading the config file (traefik.toml)
      - ${TRAEFIK_TMP_ROUTE}:/tmp
    labels:
      - "traefik.frontend.rule=Host:monitor.${DOMAIN}" # domain to access the dashboard odd traefik
      - "traefik.port=8080" # default port to access the dashboard for traefik
    container_name: traefik
    restart: always

networks:
  proxy: # new docker network to work
    external: true