apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-game-controller
rules:
- apiGroups: ["retro.sparkfabrik.com"]
  resources: ["games", "games/status"]
  verbs: ["*"]
- apiGroups: ["",]
  resources: ["configmaps", "events", "services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]