apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-game-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-game-controller
subjects:
  - kind: ServiceAccount
    name: game-controller-service-account
    namespace: games