---
  - name: Gather facts about all VPCs
    hosts: local
    connection: local
    gather_facts: False
  
    tasks:
      - name: Get facts about all VPCs
        register: all_vpc_net_facts
        ec2_vpc_net_facts:
          region: us-west-2
        
      - debug:
          var: all_vpc_net_facts
