---
  - name: Terminate EC2 Instance(s)
    hosts: local
    connection: local
    gather_facts: False

    tasks:
      - name: Terminate an EC2 Instance
        ec2: 
          state: "absent"
          region: us-west-2
          instance_ids: <instance id>
