---
  - name: Gather facts about Network ACLs
    hosts: local
    connection: local
    gather_facts: False
  
    tasks:
      - name: Get All NACLS
        register: all_nacls
        ec2_vpc_nacl_facts:
          region: us-west-2
        
      - debug:
          var: all_nacls
