---
- name: Install and configure PHP 7.2, PHP-FPM and Composer
  hosts: webservers
  remote_user: root
  vars_files:
    - ../vars/php.yaml
    - ../vars/apache.yaml
  roles:
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - geerlingguy.composer
