apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: websites
  name: nfs-disk1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.245.252.122
    path: "/"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: websites
  name: nfs-disk1-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi