---
adminer_directory_path: /var/www/vhosts/adminer
apache_create_vhosts: true
apache_remove_default_vhost: true
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html app.php
apache_vhosts:
  - servername: "adminer.{{ inventory_hostname }}"
    documentroot: "{{ adminer_directory_path }}"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ adminer_directory_path }}"
      RewriteEngine on
      RewriteCond %{SERVER_NAME} =adminer.{{ inventory_hostname }}
      RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
apache_mods_enabled:
  - rewrite.load
  - headers.load
  - ssl.load
  - proxy.load
  - proxy_http.load
