{
 "title": "Latency & Traffic & Errors",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values(nginx_http_request_duration_seconds_bucket, path)"
    }
   },
   {
    "name": "status",
    "query": "success : [2-3].*,error : [4-5].*"
   },
   { "name": "method", "query": "GET,POST,PUT,DELETE" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"nginx.antonputra.pvt|apache.antonputra.pvt\"}[20s])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\"nginx.antonputra.pvt|apache.antonputra.pvt\"}[20s]) + avg_over_time(node_memory_Cached_bytes{instance=~\"nginx.antonputra.pvt|apache.antonputra.pvt\"}[20s]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"nginx.antonputra.pvt|apache.antonputra.pvt\"}[20s])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"nginx.antonputra.pvt|apache.antonputra.pvt\"}[20s])))\n",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(axum_http_requests_total{endpoint=~\"/api-nginx/devices|/api-apache/devices\"}[20s])) by (endpoint), 0.001)",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  }
 ]
}