---
- name: Cisco Playbook with Cisco Role
  connection: network_cli
  hosts: "ios-devices"
  gather_facts: false
  roles: 
    - cisco

  tasks: 
    - name: show version
      ios_command: 
        commands: show version
      
      register: output

    - name: show output
      debug:
        var: output.stdout
   
    - name: copy output to file
      copy: content="{{ output }}" dest=./output/{{ inventory_hostname }}.txt
...
