---
- name: First network playbook
  connection: network_cli
  gather_facts: false
  hosts: iosv-1
  tasks: 
    - name: show version
      ios_command: 
        commands: show version
      register: output
 
    - name: show output
      debug: 
        var: output

