---
- name: Collect IOS-XR Device Facts
  hosts: iosxrv-1
  gather_facts: False
  tasks: 
    - name: collect facts
      iosxr_facts: 
        gather_subset: all
      
      register: output

    - name: show output
      debug:
        var: output
   
...
