---
- name: IOS-XR commands with Output Evaluation
  connection: network_cli
  hosts: iosxrv-1
  tasks: 
    - name: Evaluate Output
      iosxr_command: 
        commands: 
          - show version
        wait_for: 
          - result[0] contains 'Version 6.1.3' 
      register: output

    - name: Display Output
      debug: 
        var: output

...
