service: eshop-products
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  apiGateway:
    restApiId:
      "Fn::ImportValue": SharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": SharedGW-rootResourceId
functions:
  get-products:
    handler: handler.getProducts
    events:
      - http:
          path: products/list
          method: get
