version: "3"

services:

  whoogle-search:
    image: benbusby/whoogle-search
    container_name: whoogle
    hostname: whoogle-search
    restart: unless-stopped
    ports:
      - "8200:5000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
#     - WHOOGLE_USER=user       #optional
#     - WHOOGLE_PASS=p4ssw0rd   #optional
  