---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "foo.fullname" . }}-database-migration"
  labels:
    {{- include "foo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: database-migration
        image: app
        imagePullPolicy: IfNotPresent
        command: ['/usr/local/bin/db-migration']
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1

