apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: my-configmap
  files:
  - configmap.yaml

secretGenerator:
- name: my-secret
  env:
  - name: USERNAME
    valueFrom:
      configMapKeyRef:
        name: my-configmap
        key: username
  - name: PASSWORD
    valueFrom:
      configMapKeyRef:
        name: my-configmap
        key: password