---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops-by-example
  region: us-east-1
availabilityZones: 
- us-east-1a
- us-east-1b
nodeGroups:
- name: nodes-general
  labels:
      role: workers
  instanceType: t2.small
  desiredCapacity: 1
  volumeSize: 20
