apiVersion: v1
kind: Service
metadata:
  namespace: websites
  name: nfs-disk1-server
spec:
  clusterIP: 10.245.252.122
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-disk1-server