apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: websites
  name: nfs-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfs-busybox
  template:
    metadata:
      labels:
        name: nfs-busybox
    spec:
      containers:
        - image: busybox
          imagePullPolicy: Always
          name: busybox
          volumeMounts:
            # name must match the volume name below
            - name: disk1-pvc-nfs
              mountPath: "/mnt"
              subPath: shared-storage/busybox-demo
      volumes:
        - name: disk1-pvc-nfs
          persistentVolumeClaim:
            claimName: nfs-disk1-pvc