service: serverless-github-check

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  profile: personal
  region: eu-west-1
  environment:
    GITHUB_TOKEN: ${ssm:githubToken}

functions:
  githubCheck:
    handler: handler.githubCheck
    events:
      - http:
          path: webhook
          method: post
          cors: true
