---
- name: NX-OS command with JSON output
  connection: network_cli
  hosts: nxosv-1
  tasks: 
    - name: show version in json output
      nxos_command: 
        commands: 
          - command: show version
            output: json
      
      register: output

    - name: show output
      debug:
        var: output
...
