---
- name: Collect NX-OS Device Facts
  connection: network_cli
  hosts: nxos-devices
  tasks: 
    - name: collect facts
      nxos_facts: 
        gather_subset: all
      
      register: output

    - name: show output
      debug:
        var: output
...
