apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: thanos-sidecar-svc
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: grpc
    port: 10901
    targetPort: 10901
  selector:
    app: prometheus
    prometheus: k8s
