---
- name: Template Example
  hosts: localhost
  gather_facts: false
  connection: local

  tasks: 
    - name: Generate Config
      template: src=./config_templates/spine.j2 dest=./configs/{{ item.hostname }}.txt

      with_items: 
        - { hostname: R1, loopback: '1.1.1.1 255.255.255.255' }
        - { hostname: R2, loopback: '2.2.2.2 255.255.255.255' }

