---
- name: Template Example
  hosts: localhost
  gather_facts: false
  connection: local

  tasks: 
    - name: Generate Config
      template: src=./config_templates/leaf.j2 dest=./configs/{{ item.hostname }}.txt

      with_items: 
        - { hostname: R3, loopback: '3.3.3.3 255.255.255.255' }
        - { hostname: R4, loopback: '4.4.4.4 255.255.255.255' }

