apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster-2
spec:
  replicas: 1
  secretName: my-cluster-secret-2
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secret-2
type: Opaque
data:
  ROOT_PASSWORD: cm9vdA==
