GE- PROTON: https://github.com/GloriousEggroll/pr...
Heroic Games Launcher: https://heroicgameslauncher.com/
Lutris: https://lutris.net/
MangoHud: https://github.com/flightlessmango/Ma...
GameMode: https://github.com/FeralInteractive/g...
vkBasalt: https://github.com/DadSchoorse/vkBasalt