version: 2
jobs:
  build:
    machine: true
    steps:
     - add_ssh_keys: 
        fingerprints:
          -"{CIRCLECIfingerprint}"
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t {repositorio:$CIRCLE_SHA1}
     - run: docker push {repositorio:$CIRCLE_SHA1}
     - run: ssh -o StrictHostKeyChecking=no root@username "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"